[package]
name = "rendezvous"
version = "0.1.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
license = "AGPL-3.0"
publish = false

[[bin]]
name = "rendezvous"
path = "src/main.rs"

[dependencies]
env_logger = "0.5"
error-chain = "0.10"
futures-await = "0.1"
futures-cpupool = "0.1.8"
irc = "0.12.3"
log = "0.4"
multiqueue = "0.3"
parking_lot = "0.4"
serenity = "0.4"
tokio-core = "0.1.9"
typemap = "0.3"

[dev-dependencies]
rand = "0.3"

[profile.dev]
opt-level = 0
codegen-units = 4
lto = false

[profile.release]
opt-level = 3
lto = true
debug = true
